name: 'Covid Tracker UI CI/CD'
on:
  push:
    branches:
        - master
jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Setup Yarn
        run: npm install -g yarn
      - name: 'Install Packages'
        run: |
          yarn
      - name: 'Build Application'
        run: |
          yarn build:prod
      - name: Sync files with S3
        run: |
          aws s3 sync ./dist/ncov-tracker/ s3://covid-tracker-ui-prod
          aws cloudfront create-invalidation --distribution-id 'E1FQR0D7SQEOUW' --paths '/*'
